### ISSUE TITLE
PR classification use of state and merged variables

### ISSUE THREAD

**Issue by MaximMoinat** [PiotrZakrzewski/merge-chance#1]
https://github.com/PiotrZakrzewski/oss-responsiveness/blob/b50a5149428e05c09ac20c29d5bae55bd8c0c198/score.py#L27-L30

In this logic, do you actually need the `merge` variable? 

I would say, the `MERGED` and `CLOSED` states are exclusive. The first is always merged, the second is never merged.

**Comment by PiotrZakrzewski** [comment]
This is true. This is a remnant of REST-api format I initially used. REST API did not have a merged status, only OPEN/CLOSED.
👍🏿

**Comment by MaximMoinat** [comment]
Thanks, that explains! Btw: I am trying to adapt the script to create a simple overview of these stats for all repositories of an organisation. And hopefully get some GraphQL experience while doing so :).
