### ISSUE TITLE
Checking all the repositories of an organization

### ISSUE THREAD

**Issue by aminya** [PiotrZakrzewski/merge-chance#7]
It would be nice if we can enter the name of a whole organization.

**Comment by PiotrZakrzewski** [comment]
nice idea. One limitation I am struggling with for now is how much latency fetching data from GitHub introduces. After improving my methodology the amount of data I need to fetch has increased, fetching data for entire organization would require an order of magnitude more (some orgs have 100s of repos). But - as soon as I fix my current issues (methodology, data quality, latency) I may work on some rankings, if I head this way stacking org data is a logical way to go :)

Thanks for your feedback!
